"""Initial migration

Revision ID: 23eb3a56beea
Revises: 
Create Date: 2025-12-03 09:02:29.238151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23eb3a56beea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('power_watts', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smart_devices_id'), 'smart_devices', ['id'], unique=False)
    op.create_index(op.f('ix_smart_devices_name'), 'smart_devices', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smart_devices_name'), table_name='smart_devices')
    op.drop_index(op.f('ix_smart_devices_id'), table_name='smart_devices')
    op.drop_table('smart_devices')
    # ### end Alembic commands ###
